server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lin-Huang/config-place-demo/
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:1111/eureka/